// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Pokemon$ReasonDojoPokedex = require("./Pokemon.bs.js");
var Pokemons$ReasonDojoPokedex = require("./Pokemons.bs.js");

var component = ReasonReact.reducerComponent("App");

var fonts = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'";

var style = {
  fontFamily: fonts,
  margin: "auto",
  marginTop: "24px",
  width: "800px"
};

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherID = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      var match = url[/* path */0];
                      if (match && !match[1]) {
                        return Curry._1(self[/* send */3], /* ShowSingle */[Caml_format.caml_int_of_string(match[0])]);
                      } else {
                        return Curry._1(self[/* send */3], /* ShowList */0);
                      }
                    }));
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            return ReasonReact.Router[/* unwatchUrl */2](watcherID);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              var content = match ? ReasonReact.element(undefined, undefined, Pokemon$ReasonDojoPokedex.make(match[0], /* array */[])) : ReasonReact.element(undefined, undefined, Pokemons$ReasonDojoPokedex.make(/* array */[]));
              return React.createElement("div", {
                          style: style
                        }, React.createElement("div", undefined, "Pokedex!"), content);
            }),
          /* initialState */(function (param) {
              var match = ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0)[/* path */0];
              if (match && !match[1]) {
                return /* Single */[Caml_format.caml_int_of_string(match[0])];
              } else {
                return /* List */0;
              }
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              if (action) {
                return /* Update */Block.__(0, [/* Single */[action[0]]]);
              } else {
                return /* Update */Block.__(0, [/* List */0]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.fonts = fonts;
exports.style = style;
exports.make = make;
/* component Not a pure module */
