// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Api$ReasonDojoPokedex = require("./Api.bs.js");
var Link$ReasonDojoPokedex = require("./Link.bs.js");

var ppx_printed_query = "query getPokemons($first: Int, $after: String, $search: String)  {\npokemon: Pokemon(first: $first, after: $after, filter: {identifierLike: $search})  {\ntotalCount  \npageInfo  {\nendCursor  \n}\n\nedges  {\nnode  {\nid  \nenglishName  \nidentifier  \nsprites  {\nnormal  {\nmale  {\nfront  \n}\n\n}\n\n}\n\n}\n\n}\n\n}\n\n}\n";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match !== undefined) {
    var match$1 = Js_dict.get(Caml_option.valFromOption(match), "pokemon");
    var tmp;
    if (match$1 !== undefined) {
      var value$1 = Caml_option.valFromOption(match$1);
      var match$2 = Js_json.decodeNull(value$1);
      if (match$2 !== undefined) {
        tmp = undefined;
      } else {
        var match$3 = Js_json.decodeObject(value$1);
        var tmp$1;
        if (match$3 !== undefined) {
          var value$2 = Caml_option.valFromOption(match$3);
          var match$4 = Js_dict.get(value$2, "totalCount");
          var tmp$2;
          if (match$4 !== undefined) {
            var value$3 = Caml_option.valFromOption(match$4);
            var match$5 = Js_json.decodeNull(value$3);
            if (match$5 !== undefined) {
              tmp$2 = undefined;
            } else {
              var match$6 = Js_json.decodeNumber(value$3);
              tmp$2 = match$6 !== undefined ? match$6 | 0 : Js_exn.raiseError("graphql_ppx: Expected int, got " + JSON.stringify(value$3));
            }
          } else {
            tmp$2 = undefined;
          }
          var match$7 = Js_dict.get(value$2, "pageInfo");
          var tmp$3;
          if (match$7 !== undefined) {
            var match$8 = Js_json.decodeObject(Caml_option.valFromOption(match$7));
            if (match$8 !== undefined) {
              var match$9 = Js_dict.get(Caml_option.valFromOption(match$8), "endCursor");
              var tmp$4;
              if (match$9 !== undefined) {
                var value$4 = Caml_option.valFromOption(match$9);
                var match$10 = Js_json.decodeNull(value$4);
                if (match$10 !== undefined) {
                  tmp$4 = undefined;
                } else {
                  var match$11 = Js_json.decodeString(value$4);
                  tmp$4 = match$11 !== undefined ? match$11 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$4));
                }
              } else {
                tmp$4 = undefined;
              }
              tmp$3 = {
                endCursor: tmp$4
              };
            } else {
              tmp$3 = Js_exn.raiseError("graphql_ppx: Object is not a value");
            }
          } else {
            tmp$3 = Js_exn.raiseError("graphql_ppx: Field pageInfo on type PokemonConnection is missing");
          }
          var match$12 = Js_dict.get(value$2, "edges");
          var tmp$5;
          if (match$12 !== undefined) {
            var value$5 = Caml_option.valFromOption(match$12);
            var match$13 = Js_json.decodeNull(value$5);
            if (match$13 !== undefined) {
              tmp$5 = undefined;
            } else {
              var match$14 = Js_json.decodeArray(value$5);
              tmp$5 = match$14 !== undefined ? match$14.map((function (value) {
                        var match = Js_json.decodeNull(value);
                        if (match !== undefined) {
                          return undefined;
                        } else {
                          var match$1 = Js_json.decodeObject(value);
                          var tmp;
                          if (match$1 !== undefined) {
                            var match$2 = Js_dict.get(Caml_option.valFromOption(match$1), "node");
                            var tmp$1;
                            if (match$2 !== undefined) {
                              var value$1 = Caml_option.valFromOption(match$2);
                              var match$3 = Js_json.decodeNull(value$1);
                              if (match$3 !== undefined) {
                                tmp$1 = undefined;
                              } else {
                                var match$4 = Js_json.decodeObject(value$1);
                                var tmp$2;
                                if (match$4 !== undefined) {
                                  var value$2 = Caml_option.valFromOption(match$4);
                                  var match$5 = Js_dict.get(value$2, "id");
                                  var tmp$3;
                                  if (match$5 !== undefined) {
                                    var value$3 = Caml_option.valFromOption(match$5);
                                    var match$6 = Js_json.decodeNull(value$3);
                                    if (match$6 !== undefined) {
                                      tmp$3 = undefined;
                                    } else {
                                      var match$7 = Js_json.decodeString(value$3);
                                      tmp$3 = match$7 !== undefined ? match$7 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$3));
                                    }
                                  } else {
                                    tmp$3 = undefined;
                                  }
                                  var match$8 = Js_dict.get(value$2, "englishName");
                                  var tmp$4;
                                  if (match$8 !== undefined) {
                                    var value$4 = Caml_option.valFromOption(match$8);
                                    var match$9 = Js_json.decodeNull(value$4);
                                    if (match$9 !== undefined) {
                                      tmp$4 = undefined;
                                    } else {
                                      var match$10 = Js_json.decodeString(value$4);
                                      tmp$4 = match$10 !== undefined ? match$10 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$4));
                                    }
                                  } else {
                                    tmp$4 = undefined;
                                  }
                                  var match$11 = Js_dict.get(value$2, "identifier");
                                  var tmp$5;
                                  if (match$11 !== undefined) {
                                    var value$5 = Caml_option.valFromOption(match$11);
                                    var match$12 = Js_json.decodeNull(value$5);
                                    if (match$12 !== undefined) {
                                      tmp$5 = undefined;
                                    } else {
                                      var match$13 = Js_json.decodeString(value$5);
                                      tmp$5 = match$13 !== undefined ? match$13 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$5));
                                    }
                                  } else {
                                    tmp$5 = undefined;
                                  }
                                  var match$14 = Js_dict.get(value$2, "sprites");
                                  var tmp$6;
                                  if (match$14 !== undefined) {
                                    var value$6 = Caml_option.valFromOption(match$14);
                                    var match$15 = Js_json.decodeNull(value$6);
                                    if (match$15 !== undefined) {
                                      tmp$6 = undefined;
                                    } else {
                                      var match$16 = Js_json.decodeObject(value$6);
                                      var tmp$7;
                                      if (match$16 !== undefined) {
                                        var match$17 = Js_dict.get(Caml_option.valFromOption(match$16), "normal");
                                        var tmp$8;
                                        if (match$17 !== undefined) {
                                          var value$7 = Caml_option.valFromOption(match$17);
                                          var match$18 = Js_json.decodeNull(value$7);
                                          if (match$18 !== undefined) {
                                            tmp$8 = undefined;
                                          } else {
                                            var match$19 = Js_json.decodeObject(value$7);
                                            var tmp$9;
                                            if (match$19 !== undefined) {
                                              var match$20 = Js_dict.get(Caml_option.valFromOption(match$19), "male");
                                              var tmp$10;
                                              if (match$20 !== undefined) {
                                                var value$8 = Caml_option.valFromOption(match$20);
                                                var match$21 = Js_json.decodeNull(value$8);
                                                if (match$21 !== undefined) {
                                                  tmp$10 = undefined;
                                                } else {
                                                  var match$22 = Js_json.decodeObject(value$8);
                                                  var tmp$11;
                                                  if (match$22 !== undefined) {
                                                    var match$23 = Js_dict.get(Caml_option.valFromOption(match$22), "front");
                                                    var tmp$12;
                                                    if (match$23 !== undefined) {
                                                      var value$9 = Caml_option.valFromOption(match$23);
                                                      var match$24 = Js_json.decodeNull(value$9);
                                                      if (match$24 !== undefined) {
                                                        tmp$12 = undefined;
                                                      } else {
                                                        var match$25 = Js_json.decodeString(value$9);
                                                        tmp$12 = match$25 !== undefined ? match$25 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$9));
                                                      }
                                                    } else {
                                                      tmp$12 = undefined;
                                                    }
                                                    tmp$11 = {
                                                      front: tmp$12
                                                    };
                                                  } else {
                                                    tmp$11 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                                                  }
                                                  tmp$10 = Caml_option.some(tmp$11);
                                                }
                                              } else {
                                                tmp$10 = undefined;
                                              }
                                              tmp$9 = {
                                                male: tmp$10
                                              };
                                            } else {
                                              tmp$9 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                                            }
                                            tmp$8 = Caml_option.some(tmp$9);
                                          }
                                        } else {
                                          tmp$8 = undefined;
                                        }
                                        tmp$7 = {
                                          normal: tmp$8
                                        };
                                      } else {
                                        tmp$7 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                                      }
                                      tmp$6 = Caml_option.some(tmp$7);
                                    }
                                  } else {
                                    tmp$6 = undefined;
                                  }
                                  tmp$2 = {
                                    id: tmp$3,
                                    englishName: tmp$4,
                                    identifier: tmp$5,
                                    sprites: tmp$6
                                  };
                                } else {
                                  tmp$2 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                                }
                                tmp$1 = Caml_option.some(tmp$2);
                              }
                            } else {
                              tmp$1 = undefined;
                            }
                            tmp = {
                              node: tmp$1
                            };
                          } else {
                            tmp = Js_exn.raiseError("graphql_ppx: Object is not a value");
                          }
                          return Caml_option.some(tmp);
                        }
                      })) : Js_exn.raiseError("graphql_ppx: Expected array, got " + JSON.stringify(value$5));
            }
          } else {
            tmp$5 = undefined;
          }
          tmp$1 = {
            totalCount: tmp$2,
            pageInfo: tmp$3,
            edges: tmp$5
          };
        } else {
          tmp$1 = Js_exn.raiseError("graphql_ppx: Object is not a value");
        }
        tmp = Caml_option.some(tmp$1);
      }
    } else {
      tmp = undefined;
    }
    return {
            pokemon: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function make(first, after, search, param) {
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[
                /* tuple */[
                  "first",
                  first !== undefined ? first : null
                ],
                /* tuple */[
                  "after",
                  after !== undefined ? after : null
                ],
                /* tuple */[
                  "search",
                  search !== undefined ? search : null
                ]
              ]),
          parse: parse
        };
}

function makeWithVariables(variables) {
  var first = variables.first;
  var after = variables.after;
  var search = variables.search;
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[
                /* tuple */[
                  "first",
                  first !== undefined ? first : null
                ],
                /* tuple */[
                  "after",
                  after !== undefined ? after : null
                ],
                /* tuple */[
                  "search",
                  search !== undefined ? search : null
                ]
              ]),
          parse: parse
        };
}

function ret_type(f) {
  return /* module */[];
}

var MT_Ret = /* module */[];

var Query = /* module */[
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var component = ReasonReact.reducerComponent("PokemonList");

function decode(response) {
  var match = response.pokemon;
  var totalCount = match !== undefined ? Caml_option.valFromOption(match).totalCount : undefined;
  var match$1 = response.pokemon;
  var match$2 = match$1 !== undefined ? Caml_option.some(Caml_option.valFromOption(match$1).pageInfo) : undefined;
  var endCursor = match$2 !== undefined ? Caml_option.valFromOption(match$2).endCursor : undefined;
  var match$3 = response.pokemon;
  var edges = match$3 !== undefined ? Caml_option.valFromOption(match$3).edges : undefined;
  var pokemons = edges !== undefined ? Belt_List.map(Belt_List.keep(Belt_List.fromArray(Belt_Array.map(edges, (function (edge) {
                        var match = edge !== undefined ? Caml_option.valFromOption(edge).node : undefined;
                        var id = match !== undefined ? Caml_option.valFromOption(match).id : undefined;
                        var match$1 = edge !== undefined ? Caml_option.valFromOption(edge).node : undefined;
                        var englishName = match$1 !== undefined ? Caml_option.valFromOption(match$1).englishName : undefined;
                        var match$2 = edge !== undefined ? Caml_option.valFromOption(edge).node : undefined;
                        var match$3 = match$2 !== undefined ? Caml_option.valFromOption(match$2).sprites : undefined;
                        var match$4 = match$3 !== undefined ? Caml_option.valFromOption(match$3).normal : undefined;
                        var match$5 = match$4 !== undefined ? Caml_option.valFromOption(match$4).male : undefined;
                        var sprite = match$5 !== undefined ? Caml_option.valFromOption(match$5).front : undefined;
                        return Belt_Option.flatMap(id, (function (id) {
                                      return Belt_Option.flatMap(englishName, (function (englishName) {
                                                    return Belt_Option.flatMap(sprite, (function (sprite) {
                                                                  return /* record */[
                                                                          /* id */Caml_format.caml_int_of_string(id),
                                                                          /* englishName */englishName,
                                                                          /* sprite */sprite
                                                                        ];
                                                                }));
                                                  }));
                                    }));
                      }))), Belt_Option.isSome), Belt_Option.getExn) : /* [] */0;
  var param = Belt_Option.flatMap(totalCount, (function (totalCount) {
          return Belt_Option.flatMap(endCursor, (function (endCursor) {
                        return /* record */[
                                /* totalCount */totalCount,
                                /* endCursor */endCursor,
                                /* pokemons */pokemons
                              ];
                      }));
        }));
  if (param !== undefined) {
    return /* Ok */Block.__(0, [param]);
  } else {
    return /* Error */Block.__(1, ["bad data"]);
  }
}

function appendToList(currentData, newData) {
  return /* record */[
          /* totalCount */currentData[/* totalCount */0],
          /* endCursor */newData[/* endCursor */1],
          /* pokemons */Belt_List.concat(currentData[/* pokemons */2], newData[/* pokemons */2])
        ];
}

function loadMore(currentData, self) {
  Api$ReasonDojoPokedex.sendQuery(make(undefined, currentData[/* endCursor */1], undefined, /* () */0)).then((function (result) {
          if (result.tag) {
            Curry._1(self[/* send */3], /* SetError */Block.__(1, [result[0]]));
          } else {
            var match = decode(result[0]);
            if (match.tag) {
              Curry._1(self[/* send */3], /* SetError */Block.__(1, [match[0]]));
            } else {
              Curry._1(self[/* send */3], /* LoadData */Block.__(0, [appendToList(currentData, match[0])]));
            }
          }
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

function make$1(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              Api$ReasonDojoPokedex.sendQuery(make(50, undefined, undefined, /* () */0)).then((function (r) {
                      if (r.tag) {
                        Curry._1(self[/* send */3], /* SetError */Block.__(1, [r[0]]));
                      } else {
                        var match = decode(r[0]);
                        if (match.tag) {
                          Curry._1(self[/* send */3], /* SetError */Block.__(1, [match[0]]));
                        } else {
                          Curry._1(self[/* send */3], /* LoadData */Block.__(0, [match[0]]));
                        }
                      }
                      return Promise.resolve(/* () */0);
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              if (typeof match === "number") {
                return React.createElement("div", undefined, "Loading...");
              } else if (match.tag) {
                var data = match[0];
                var pokemons = Belt_List.toArray(Belt_List.map(data[/* pokemons */2], (function (pokemon) {
                            return React.createElement("div", {
                                        key: String(pokemon[/* id */0])
                                      }, ReasonReact.element(undefined, undefined, Link$ReasonDojoPokedex.make("/" + String(pokemon[/* id */0]), React.createElement("div", undefined, React.createElement("img", {
                                                        src: pokemon[/* sprite */2]
                                                      }), pokemon[/* englishName */1]))));
                          })));
                return React.createElement("div", undefined, React.createElement("div", undefined, pokemons), React.createElement("button", {
                                onClick: (function (param) {
                                    return Curry._2(self[/* handle */0], loadMore, data);
                                  })
                              }, "Load More"));
              } else {
                return React.createElement("div", undefined, match[0]);
              }
            }),
          /* initialState */(function (param) {
              return /* Loading */0;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              if (action.tag) {
                return /* Update */Block.__(0, [/* Error */Block.__(0, [action[0]])]);
              } else {
                return /* Update */Block.__(0, [/* Data */Block.__(1, [action[0]])]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Query = Query;
exports.component = component;
exports.decode = decode;
exports.appendToList = appendToList;
exports.loadMore = loadMore;
exports.make = make$1;
/* component Not a pure module */
